edges:
  edge-m0-0:
    mqtt_broker_url: mqtt://10.0.10.11:1883

  edge-m0-1:
    mqtt_broker_url: mqtt://10.0.10.12:1883

  edge-m1-0:
    mqtt_broker_url: mqtt://10.0.20.11:1883

  edge-m2-0:
    mqtt_broker_url: mqtt://10.0.30.11:1883