services:

  mqtt-edge-0:
    image: eclipse-mosquitto:2
    container_name: mqtt-edge-0
    ports:
      - "18830:1883"
    volumes:
      - ../mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    restart: unless-stopped

  mqtt-edge-1:
    image: eclipse-mosquitto:2
    container_name: mqtt-edge-1
    ports:
      - "18831:1883"
    volumes:
      - ../mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    restart: unless-stopped

  mqtt-edge-2:
    image: eclipse-mosquitto:2
    container_name: mqtt-edge-2
    ports:
      - "18832:1883"
    volumes:
      - ../mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    restart: unless-stopped

  mqtt-edge-3:
    image: eclipse-mosquitto:2
    container_name: mqtt-edge-3
    ports:
      - "18833:1883"
    volumes:
      - ../mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    restart: unless-stopped

  mqtt-edge-4:
    image: eclipse-mosquitto:2
    container_name: mqtt-edge-4
    ports:
      - "18834:1883"
    volumes:
      - ../mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    restart: unless-stopped

  mqtt-edge-5:
    image: eclipse-mosquitto:2
    container_name: mqtt-edge-5
    ports:
      - "18835:1883"
    volumes:
      - ../mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    restart: unless-stopped

  mqtt-edge-6:
    image: eclipse-mosquitto:2
    container_name: mqtt-edge-6
    ports:
      - "18836:1883"
    volumes:
      - ../mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    restart: unless-stopped

  mqtt-edge-7:
    image: eclipse-mosquitto:2
    container_name: mqtt-edge-7
    ports:
      - "18837:1883"
    volumes:
      - ../mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    restart: unless-stopped

  mqtt-edge-8:
    image: eclipse-mosquitto:2
    container_name: mqtt-edge-8
    ports:
      - "18838:1883"
    volumes:
      - ../mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    restart: unless-stopped

  mqtt-edge-9:
    image: eclipse-mosquitto:2
    container_name: mqtt-edge-9
    ports:
      - "18839:1883"
    volumes:
      - ../mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    restart: unless-stopped

  mqtt-edge-10:
    image: eclipse-mosquitto:2
    container_name: mqtt-edge-10
    ports:
      - "18840:1883"
    volumes:
      - ../mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    restart: unless-stopped

  mqtt-edge-11:
    image: eclipse-mosquitto:2
    container_name: mqtt-edge-11
    ports:
      - "18841:1883"
    volumes:
      - ../mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    restart: unless-stopped

  mqtt-edge-12:
    image: eclipse-mosquitto:2
    container_name: mqtt-edge-12
    ports:
      - "18842:1883"
    volumes:
      - ../mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    restart: unless-stopped