package main

import (
	"encoding/csv"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

const (
	topologyPath = "dataset/output/kmeans_topology.csv"
	outputPath   = "deploy/compose/continuum.generated.yml"

	mqttBasePort = 18830
)

type EdgeDeployment struct {
	EdgeID      string
	EdgeNumber  int
	SensorCount int
	MQTTPort    int
}

func main() {
	edges, err := loadEdges(topologyPath)
	if err != nil {
		panic(err)
	}

	if len(edges) == 0 {
		panic("nessun Edge trovato nella topologia")
	}

	compose := buildCompose(edges)

	err = os.MkdirAll(
		filepath.Dir(outputPath),
		0755,
	)
	if err != nil {
		panic(err)
	}

	err = os.WriteFile(
		outputPath,
		[]byte(compose),
		0644,
	)
	if err != nil {
		panic(err)
	}

	fmt.Printf(
		"Topologia letta: %d Edge\n\n",
		len(edges),
	)

	for _, edge := range edges {
		fmt.Printf(
			"%s -> sensors=%d mqtt=localhost:%d\n",
			edge.EdgeID,
			edge.SensorCount,
			edge.MQTTPort,
		)
	}

	fmt.Printf(
		"\nGenerato: %s\n",
		outputPath,
	)
}

func loadEdges(
	path string,
) ([]EdgeDeployment, error) {
	file, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer file.Close()

	reader := csv.NewReader(file)
	reader.Comma = ','

	header, err := reader.Read()
	if err != nil {
		return nil, err
	}

	columns := buildColumnIndex(header)

	edgeIDIndex, err := requiredColumn(
		columns,
		"edge_id",
	)
	if err != nil {
		return nil, err
	}

	sensorCounts := make(
		map[string]int,
	)

	for {
		row, err := reader.Read()

		if err == io.EOF {
			break
		}

		if err != nil {
			return nil, err
		}

		edgeID := strings.TrimSpace(
			row[edgeIDIndex],
		)

		if edgeID == "" {
			return nil,
				fmt.Errorf(
					"edge_id vuoto nella topologia",
				)
		}

		sensorCounts[edgeID]++
	}

	edges := make(
		[]EdgeDeployment,
		0,
		len(sensorCounts),
	)

	for edgeID, sensorCount := range sensorCounts {
		edgeNumber, err := parseEdgeNumber(
			edgeID,
		)
		if err != nil {
			return nil, err
		}

		edges = append(
			edges,
			EdgeDeployment{
				EdgeID:      edgeID,
				EdgeNumber:  edgeNumber,
				SensorCount: sensorCount,
				MQTTPort:    mqttBasePort + edgeNumber,
			},
		)
	}

	sort.Slice(
		edges,
		func(i int, j int) bool {
			return edges[i].EdgeNumber <
				edges[j].EdgeNumber
		},
	)

	return edges, nil
}

func parseEdgeNumber(
	edgeID string,
) (int, error) {
	const prefix = "edge-"

	if !strings.HasPrefix(
		edgeID,
		prefix,
	) {
		return 0,
			fmt.Errorf(
				"edge_id non valido %q",
				edgeID,
			)
	}

	value := strings.TrimPrefix(
		edgeID,
		prefix,
	)

	edgeNumber, err := strconv.Atoi(
		value,
	)
	if err != nil {
		return 0,
			fmt.Errorf(
				"edge_id non valido %q: %w",
				edgeID,
				err,
			)
	}

	if edgeNumber < 0 {
		return 0,
			fmt.Errorf(
				"numero Edge negativo in %q",
				edgeID,
			)
	}

	return edgeNumber, nil
}

func buildColumnIndex(
	header []string,
) map[string]int {
	columns := make(
		map[string]int,
	)

	for index, name := range header {
		columns[strings.TrimSpace(name)] = index
	}

	return columns
}

func requiredColumn(
	columns map[string]int,
	name string,
) (int, error) {
	index, found := columns[name]

	if !found {
		return 0,
			fmt.Errorf(
				"colonna %q non trovata",
				name,
			)
	}

	return index, nil
}

func buildCompose(
	edges []EdgeDeployment,
) string {
	var builder strings.Builder

	builder.WriteString(
		"# Code generated by cmd/deploygen. DO NOT EDIT.\n",
	)

	builder.WriteString(
		"# Source: dataset/output/kmeans_topology.csv\n\n",
	)

	builder.WriteString(
		"services:\n\n",
	)

	for _, edge := range edges {
		mqttService := "mqtt-" + edge.EdgeID
		network := "zone-" + edge.EdgeID

		fmt.Fprintf(
			&builder,
			"  # %s: %d sensors\n",
			edge.EdgeID,
			edge.SensorCount,
		)

		fmt.Fprintf(
			&builder,
			"  %s:\n",
			mqttService,
		)

		builder.WriteString(
			"    image: eclipse-mosquitto:2\n",
		)

		fmt.Fprintf(
			&builder,
			"    container_name: %s\n",
			mqttService,
		)

		builder.WriteString(
			"    ports:\n",
		)

		fmt.Fprintf(
			&builder,
			"      - \"%d:1883\"\n",
			edge.MQTTPort,
		)

		builder.WriteString(
			"    volumes:\n",
		)

		builder.WriteString(
			"      - ../mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro\n",
		)

		builder.WriteString(
			"    healthcheck:\n",
		)

		builder.WriteString(
			"      test: [\"CMD\", \"mosquitto_pub\", \"-h\", \"localhost\", \"-p\", \"1883\", \"-t\", \"healthcheck\", \"-m\", \"ping\"]\n",
		)

		builder.WriteString(
			"      interval: 5s\n",
		)

		builder.WriteString(
			"      timeout: 3s\n",
		)

		builder.WriteString(
			"      retries: 10\n",
		)

		builder.WriteString(
			"    restart: unless-stopped\n",
		)

		builder.WriteString(
			"    networks:\n",
		)

		fmt.Fprintf(
			&builder,
			"      - %s\n\n",
			network,
		)

		fmt.Fprintf(
			&builder,
			"  %s:\n",
			edge.EdgeID,
		)

		builder.WriteString(
			"    image: continuum-edge:local\n",
		)

		fmt.Fprintf(
			&builder,
			"    container_name: %s\n",
			edge.EdgeID,
		)

		builder.WriteString(
			"    environment:\n",
		)

		fmt.Fprintf(
			&builder,
			"      EDGE_ID: \"%s\"\n",
			edge.EdgeID,
		)

		fmt.Fprintf(
			&builder,
			"      MQTT_BROKER: \"tcp://%s:1883\"\n",
			mqttService,
		)

		builder.WriteString(
			"      WINDOW_SIZE: \"${EDGE_WINDOW_SIZE:-5m}\"\n",
		)

		builder.WriteString(
			"    depends_on:\n",
		)

		fmt.Fprintf(
			&builder,
			"      %s:\n",
			mqttService,
		)

		builder.WriteString(
			"        condition: service_healthy\n",
		)

		builder.WriteString(
			"    restart: unless-stopped\n",
		)

		builder.WriteString(
			"    networks:\n",
		)

		fmt.Fprintf(
			&builder,
			"      - %s\n\n",
			network,
		)
	}

	builder.WriteString(
		"networks:\n",
	)

	for _, edge := range edges {
		fmt.Fprintf(
			&builder,
			"  zone-%s:\n",
			edge.EdgeID,
		)

		builder.WriteString(
			"    driver: bridge\n",
		)
	}

	return builder.String()
}
